apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redfish-exporter
spec:
  selector:
    matchLabels:
      app: redfish-exporter
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
