apiVersion: v1
kind: Service
metadata:
  name: redfish-exporter
  labels:
    app: redfish-exporter
spec:
  selector:
    app: redfish-exporter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: events
    - protocol: TCP
      port: 2112
      targetPort: 2112
      name: metrics
